
services:
  db:
    image: postgres:15
    container_name: conexblog-db
    restart: always
    ports:
      - '5433:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=conexblog
      - POSTGRES_USER=postgres
